# Generated by Django 3.2.18 on 2023-03-19 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('survey', 'Survey'), ('discussion', 'Discussion'), ('diary', 'Diary')], max_length=20)),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tile.tile')),
            ],
        ),
    ]
